Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile
    - tmp/**/*
    - node_modules/**/*
    - log/*
    - docker/*

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Lint/UriEscapeUnescape:
  Exclude:
    - app/controllers/v1/posts_controller.rb

Metrics/AbcSize:
  Max: 20

# ブロック内の長さ
Metrics/BlockLength:
  Enabled: false

# 一行の長さ
Metrics/LineLength:
  Max: 160

# メソッド名の長さ
Metrics/MethodLength:
  Max: 30

Naming/AccessorMethodName:
  Enabled: false

# find_by でカラムを指定して使用する
Rails/DynamicFindBy:
  Enabled: false
Rails/FindBy:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/TimeZone:
  Enabled: false

# 出力の指定
Rails/Output:
  Enabled: false

# DateTime の使用
Style/DateTime:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# !! の使用
Style/DoubleNegation:
  Enabled: false

# 文字列リテラルに対し、マジックコメントを使用していること
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

# 文字列リテラルであればシングルクォートを推奨する
Style/StringLiterals:
  Enabled: false
