version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: bundle exec unicorn -p 3000 -c /book_recorder/config/unicorn/development.rb
    ports:
      - 3000:3000
    volumes:
      - .:/book_recorder
      - ./tmp/share:/share
      - ./tmp/mysql:/var/lib/mysql
    depends_on:
      - db
    links:
      - db
      - db:database
      - db:mysql
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./tmp/share:/share
      - ./tmp/mysql:/var/lib/mysql
    env_file: ./docker/db/.mysql_env
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./tmp/share:/share
      - ./tmp/mysql:/var/lib/mysql
